### ISSUE TITLE
Should safe and unsafe results be consistently marked and/or separated?

### ISSUE THREAD

**Issue by michaellenaghan** [ecraven/r7rs-benchmarks#11]
There are two entries for Chez, effectively safe and unsafe. The fact that other entries are unlabelled makes it easy to assume that they're all "safe"—but, as the [Gambit prelude](https://github.com/ecraven/r7rs-benchmarks/blob/master/src/GambitC-prelude.scm) shows, some of them are actually "unsafe".

**Comment by ecraven** [comment]
> There are two entries for Chez, effectively safe and unsafe. The fact
> that other entries are unlabelled makes it easy to assume that they're
> all "safe"—but, as the [Gambit
> prelude](https://github.com/ecraven/r7rs-benchmarks/blob/master/src/GambitC-prelude.scm)
> shows, some of them are actually "unsafe".

Where do you see "safe" and "unsafe" for Chez? Chez has chez and petite
(as far as I understand compiled and interpreted).

For Gambit, I'd ask anyone familiar with gambitc to tell me how to
improve the prelude, I don't actually use gambit myself at all :-/

**Comment by michaellenaghan** [comment]
Hmmm, I was looking at https://www.nexoid.at/tmp/scheme-benchmark-r7rs.html thinking they were from you; now I realize nothing says they are. In any event, they show entries for `optimizelevel-2` and `optimizelevel-3`. 3, which is what the project [currently uses](https://github.com/ecraven/r7rs-benchmarks/blob/master/bench#L572), is unsafe; 2 is the default.

I guess the original question still stands, though: do you want unsafe results? If so, I'd suggest having both safe _and_ unsafe and labelling them separately.

I'll tell you what. I'll close this issue, and I'll try to put together a pull request tomorrow. Then you can decide whether or not you want the changes.
