### ISSUE TITLE
add startup time benchmark

### ISSUE THREAD

**Issue by xificurC** [ecraven/r7rs-benchmarks#33]
It would be nice to see the startup time of each scheme. Those that take very long to run can't be considered for writing unix-like one-shot tools like cat or grep. From my own trials some take extremely long to start.

**Comment by ecraven** [comment]
Time measured right now does not include startup time. I'll think about a way to actually usefully measure this.

**Comment by ecraven** [comment]
The benchmarks in general should be extended (memory usage, cpu usage, startup time, ...), I'll close this, but I'm working on a generic framework for running code on different Schemes, maybe I can measure more with that...
