### ISSUE TITLE
r7rs compatibility libraries for chez

### ISSUE THREAD

**Issue by jeback1** [ecraven/r7rs-benchmarks#34]
Thanks for maintaining this set of benchmarks.

In the 'bench' script, the chez command refers to '--libdirs /home/nex/scheme/chez'

Could you please describe how you set up the compatibility libraries for chez?

Thanks,
Jan Erik

**Comment by natethern** [comment]
I'm also waiting for an answer to this one. For now, just revert to the previous commit.

**Comment by ecraven** [comment]
See https://github.com/ecraven/chez-scheme-libraries.
My attempt at starting an r7rs compatibility layer for chez.
