### ISSUE TITLE
Implementation names in top-9 graph

### ISSUE THREAD

**Issue by svenha** [ecraven/r7rs-benchmarks#37]
The implementation names in the first two graphs of https://ecraven.github.io/r7rs-benchmarks/ seem to be consistent, except for the strange combined entry "gambit/gerbil" in the top-9 graph. Can this be split?

**Comment by ecraven** [comment]
> The implementation names in the first two graphs of
> https://ecraven.github.io/r7rs-benchmarks/ seem to be consistent,
> except for the strange combined entry "gambit/gerbil" in the top-9
> graph. Can this be split?

After much discussion, this was merged on purpose, as gerbil is built on
top of gambit, and has much the same performance. If it were counted as
two separate implementations, this would create an unfair situation for
others and these two. If they ever drift apart enough in performance,
I'll revisit this decision ;)

**Comment by svenha** [comment]
Thanks for explaining. Let's see how Gerbil evolves.
