### ISSUE TITLE
updates to match larceny versions of benchmarks

### ISSUE THREAD

**Issue by gambiteer** [ecraven/r7rs-benchmarks#39]
Will Clinger has updated his versions of a few of these benchmarks, see

http://www.larcenists.org/benchmarksAboutR7.html

This patch for fft.scm and paraffins.scm gets your versions to match his.

Brad
[patch.txt](https://github.com/ecraven/r7rs-benchmarks/files/2601719/patch.txt)

**Comment by gambiteer** [comment]
Perhaps I should say that this patch has the codes use the R7RS built-in procedure `quotient` rather than a user-defined procedure `div`.

**Comment by ecraven** [comment]
Thank you very much for this, merged.
