### ISSUE TITLE
Try this GambitC-prelude.scm

### ISSUE THREAD

**Issue by gambiteer** [ecraven/r7rs-benchmarks#4]
It allows more programs to actually compile and run:

https://gist.github.com/gambiteer/03f2d16f3ca6e76489da70b4bed71984

**Comment by ecraven** [comment]
Thank you very much, merged :)

**Comment by Hamayama** [comment]
> ;; TODO: load syntax-case here, to get syntax-rules.
> ;; google says (load "~~/syntax-case"), but that doesn't work on my machine :-/

For the above comment, the following might be valid ( 'lib' is added ).
(load "~~/lib/syntax-case.scm")
