### ISSUE TITLE
add marks for racket 7.1 and racket 6.12

### ISSUE THREAD

**Issue by milahu** [ecraven/r7rs-benchmarks#40]
can you please add benchmarks for

- racket 7.1
- racket 6.12

marking version 6.12 is interesting
cos in 7.0 racket switched to chez scheme 'backend'

adding clojure is out of scope, i guess?

**Comment by svenha** [comment]
Is not the chez backend announced as "perhaps mid–2019"? See https://blog.racket-lang.org/2018/10/racket-v7-1.html

**Comment by ecraven** [comment]
you can probably run the benchmarks yourself, I'm mostly just trying to keep up with current versions of things, and don't have the manpower to compare against older versions :-/
I don't think clojure would work, you'd have to implement all of Scheme on top of clojure, then it could maybe execute the code...
