### ISSUE TITLE
chez: precompile before execution

### ISSUE THREAD

**Issue by rajeevn1** [ecraven/r7rs-benchmarks#48]
I think for a fairer comparison, chez benchmark should precompile the program and compatibility libraries before execution, as is done with gambit.

**Comment by justinethier** [comment]
What leads you to believe they are not being compiled now?

**Comment by rajeevn1** [comment]
chez_comp function, as defined in the bench script, is empty.

**Comment by wingo** [comment]
AFAIU running a script in Chez at the command-line will compile it.  The --compile-imported-libraries flag ensures also that the r7rs support libs are compiled.  Given that the time recorded in `results.Chez` is recorded "inside" the script, there shouldn't be an issue here AFAIU.
