### ISSUE TITLE
Chicken Questions

### ISSUE THREAD

**Issue by dieggsy** [ecraven/r7rs-benchmarks#54]
I was wondering about the reasoning for the current Chicken flags (in particular C5). For example, according to [the wiki](https://wiki.call-cc.org/man/5/Using%20the%20compiler), `-O2` already includes `-optimize-leaf-routines` and `-inline`, so specifying these seems redundant. 

I was also wondering if there's any particular reason not to compile with `-O3`, or even `-C -O3`, which passes the `-O3` flag to the C compiler. I'm not entirely certain if or how these would work or break existing tests, the nature of the question is more exploratory.

**Comment by ecraven** [comment]
closed by 23ab2588870e4b99f3e778ded2b0f22fade87b2a
